[[redirects]]
  from = "/thank-you"
  to = "/thank-you.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/payment/mpesa"
  to = "/payment/mpesa.html"
  status = 200

[[redirects]]
  from = "/payment/card"
  to = "/payment/card.html"
  status = 200

[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"
